name: io_flutter_cli
description: A simple command-line application to generate simple folder and file structure for Flutter Applications.
version: 0.0.1
homepage: https://github.com/1avinashMairal/io_flutter_structure

environment:
  sdk: '>=2.12.1 <3.0.0'
  #flutter: ">=1.17.0"

dependencies:
  #flutter:
    #sdk: flutter

  args: ^2.3.1
  http: ^0.13.5
  yaml: ^3.1.1
  

dev_dependencies:
  flutter_lints: ^2.0.0
  

executables:
  io_flutter_cli:
